-- Create fotos_planta table
CREATE TABLE IF NOT EXISTS public.fotos_planta (
    id_foto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_planta BIGINT REFERENCES public.plantas(id_planta) ON DELETE CASCADE NOT NULL,
    id_tenant UUID REFERENCES public.tenants(id_tenant) NOT NULL,
    url TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notas TEXT,
    es_principal BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.fotos_planta ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Fotos tenant isolation" ON public.fotos_planta
    USING (id_tenant = (select get_current_tenant_id()));

-- Trigger to update main photo in plantas table
CREATE OR REPLACE FUNCTION public.handle_main_photo_update()
RETURNS TRIGGER AS $$
BEGIN
    -- If this photo is set as main
    IF NEW.es_principal = true THEN
        -- Unset other main photos for this plant
        UPDATE public.fotos_planta
        SET es_principal = false
        WHERE id_planta = NEW.id_planta
        AND id_foto != NEW.id_foto
        AND es_principal = true;

        -- Update the cache in plantas table
        UPDATE public.plantas
        SET image_url = NEW.url
        WHERE id_planta = NEW.id_planta;
    END IF;

    -- If deleting a main photo, clear the cache or set another one?
    -- For now, let's keep the cache but maybe we should find the latest one.
    IF (TG_OP = 'DELETE' AND OLD.es_principal = true) THEN
        UPDATE public.plantas
        SET image_url = NULL
        WHERE id_planta = OLD.id_planta;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_main_photo_change
    AFTER INSERT OR UPDATE OR DELETE ON public.fotos_planta
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_main_photo_update();

-- Create storage bucket if not exists (usually 'plantas')
-- INSERT INTO storage.buckets (id, name, public) VALUES ('plantas', 'plantas', true) ON CONFLICT DO NOTHING;

-- Migration: Copy existing photos to new table
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT * FROM public.plantas WHERE image_url IS NOT NULL LOOP
        INSERT INTO public.fotos_planta (id_planta, id_tenant, url, storage_path, es_principal, notas)
        VALUES (
            r.id_planta,
            r.id_tenant,
            r.image_url,
            'migration_legacy', -- We don't have the path easily, mark as legacy
            true,
            'Foto migrada automÃ¡ticamente'
        );
    END LOOP;
END;
$$;
